#pragma once

#include <cmath>
#include <type_traits>

namespace libdsp {

/// First-order Antiderivative Anti-Aliasing (ADAA) processor.
///
/// Template parameters:
///   F  — shaping function:       float(float)
///   AF — its first antiderivative: float(float)
///
/// ADAA computes the divided difference of the antiderivative between
/// successive samples, which is equivalent to the average of the shaping
/// function over the inter-sample interval. This suppresses aliasing
/// generated by nonlinear waveshaping.
template <typename F, typename AF>
class ADAA {
public:
    ADAA(F func, AF antiFunc)
        : m_func(func), m_antiFunc(antiFunc) {}

    void reset() {
        m_prevInput = 0.0f;
        m_prevAnti = 0.0f;
    }

    float process(float x) {
        float antiX = m_antiFunc(x);
        float diff = x - m_prevInput;
        float out;

        // When consecutive samples are very close, the divided difference
        // becomes numerically unstable — fall back to direct evaluation.
        constexpr float kEpsilon = 1.0e-7f;
        if (std::fabs(diff) < kEpsilon) {
            out = m_func(x);
        } else {
            out = (antiX - m_prevAnti) / diff;
        }

        m_prevInput = x;
        m_prevAnti = antiX;
        return out;
    }

private:
    F m_func;
    AF m_antiFunc;
    float m_prevInput = 0.0f;
    float m_prevAnti = 0.0f;
};

/// Helper to construct an ADAA processor with deduced template types.
template <typename F, typename AF>
ADAA<F, AF> makeADAA(F func, AF antiFunc) {
    return ADAA<F, AF>(func, antiFunc);
}

} // namespace libdsp
